name: core
publish_to: "none"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.2.0
  injectable: ^2.5.1
  auto_route: ^10.1.0+1
  path_provider: ^2.1.5
  path: ^1.9.1
  envied: ^1.2.0
  mocktail: ^1.0.4
  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0
  android_id: ^0.4.0
  flutter_full_screen_intent: ^0.0.8
  android_alarm_manager_plus: ^4.0.8
  receive_intent: ^0.2.7
  equatable: ^2.0.7

  encryptor:
    git:
      url: git@github.com:Tukhtamurodov-Sardorbek/encryptor.git
      ref: 051a69b87aeab54b2f66cf74cfaf5a6b98084560


dev_dependencies:
  flutter_test:
    sdk: flutter

  source_gen: ^3.1.0
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
  envied_generator: ^1.2.0
  injectable_generator: ^2.8.1

targets:
  $default:
    builders:
      union_generator:
        generate_for:
          - lib/**.dart

