name: design_system
publish_to: "none"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.0
  simple_animations: ^5.2.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.3
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.2.1

  core:
    path: ../../domain/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/
  #    - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Bold.ttf
          weight: 700
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
